version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped